#!/usr/bin/env bash
set -Eeuo pipefail

readonly THIS_DIR="$(dirname "$(readlink -f "${0}")")"
readonly BASE_KEY_ID="com.philcrockett.wtfutil"
readonly JIRA_KEY_ID="${BASE_KEY_ID}.jira"
readonly GITHUB_KEY_ID="${BASE_KEY_ID}.github"
readonly SENTRY_KEY_ID="${BASE_KEY_ID}.sentry"

secret_lookup() {
    local key_id="${1}"
    secret-tool lookup xdg:schema "${key_id}"
}

if ! WTF_JIRA_API_KEY="$(secret_lookup "${JIRA_KEY_ID}")"; then
    echo "
Please generate a Jira API token here:

    https://id.atlassian.com/manage-profile/security/api-tokens

and then paste it here:
"
    secret-tool store --label "Jira API Key" xdg:schema "${JIRA_KEY_ID}"
    WTF_JIRA_API_KEY="$(secret_lookup "${JIRA_KEY_ID}")"
fi

export WTF_JIRA_API_KEY

if ! WTF_GITHUB_TOKEN="$(secret_lookup "${GITHUB_KEY_ID}")"; then
    echo "
Please generate a GitHub personal access token here:

    https://github.com/settings/tokens

It needs the \"repo\" scope. Paste it here:
"
    secret-tool store --label "GitHub Personal Access Token" xdg:schema "${GITHUB_KEY_ID}"
    WTF_GITHUB_TOKEN="$(secret_lookup "${GITHUB_KEY_ID}")"
fi

export WTF_GITHUB_TOKEN

if ! WTF_SENTRY_TOKEN="$(secret_lookup "${SENTRY_KEY_ID}")"; then
    echo "
Please generate a Sentry auth token here:

    https://sentry.io/settings/account/api/auth-tokens/new-token/

It needs read-only permissions. Paste it here:
"
    secret-tool store --label "Sentry Auth Token" xdg:schema "${SENTRY_KEY_ID}"
    WTF_SENTRY_TOKEN="$(secret_lookup "${SENTRY_KEY_ID}")"
fi

export WTF_SENTRY_TOKEN

wtfutil --config="${THIS_DIR}/config.yml"
